
package com.yuan.ngu.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImpl", targetNamespace = "http://webservice.ngu.yuan.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.ngu.yuan.com/", className = "com.yuan.ngu.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.ngu.yuan.com/", className = "com.yuan.ngu.webservice.SayResponse")
    @Action(input = "http://webservice.ngu.yuan.com/WebServiceImpl/sayRequest", output = "http://webservice.ngu.yuan.com/WebServiceImpl/sayResponse")
    public void say(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
