server:
  context-path: /spring-boot-elasticsearch
  port: 1000

spring:
  data:
    elasticsearch:
      # elasticsearch集群名称，默认的是 elasticsearch
      cluster-name: elasticsearch
      cluster-nodes: 192.168.163.70:9300

