server:
  context-path: /spring-boot-elasticsearch
  port: 1000

spring:
  data:
    elasticsearch:
      # elasticsearch集群名称，默认的是 elasticsearch
      cluster-name: elasticsearch
      cluster-nodes: yuanngu.320.io:42365

